[package]
name = "zipkin"
version = "0.1.7"
authors = ["Steven Fackler <sfackler@palantir.com>"]
license = "Apache-2.0"
description = "A library for collecting timing information about distributed computations"
repository = "https://github.com/palantir/rust-zipkin"
documentation = "https://docs.rs/zipkin/0.1"
readme = "../README.md"
categories = ["network-programming", "web-programming"]
keywords = ["zipkin", "tracing"]

[dependencies]
data-encoding = "2.1"
log = "0.4"
rand = "0.3"
serde = { version = "1.0", optional = true, features = ["derive"] }
thread-local-object = "0.1"

[dev-dependencies]
antidote = "1.0"
